import type { Metadata } from 'next';
import './globals.css';
import QueryDataProvider from '@/data/query/queryprovider/QueryDataProvider';

export const metadata: Metadata = {
  title: 'Wealth Wise Investment',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <QueryDataProvider>{children}</QueryDataProvider>
      </body>
    </html>
  );
}
